In [2]:
import tensorflow as tf

## Initialization of Tensors

In [93]:
x = tf.constant(5)
x = tf.constant(5, shape=(1, 1))
x = tf.constant(5, shape=(2,2), dtype=tf.float32)
x = tf.constant([[1,2,3],[1,4,5]])
x = tf.ones((3,3))
x = tf.zeros((2,2))
x = tf.eye(4)
x = tf.random.normal((4,4), mean=0, stddev=2)
x = tf.random.uniform((3,3), minval=5, maxval=10)
x = tf.range(5)
x = tf.cast(x, tf.float32)
x

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 1., 2., 3., 4.], dtype=float32)>

## Mathematical operations

In [92]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])
z = tf.add(x, y)
z = x + y
z = tf.subtract(x,y)
z = x - y
z = tf.divide(x, y)
z = y / x
z = tf.multiply(x, y)
z = x * y
z = tf.tensordot(x, y, axes=1)
z = tf.reduce_sum(x*y, axis=0)
z = x ** 2

x = tf.random.normal((2,3))
y = tf.random.normal((3,5))
z1 = tf.matmul(x, y)
z2 = x @ y
z2

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[ 0.21624282,  1.3492941 , -0.2857641 , -0.5967815 ,  0.7387372 ],
       [ 0.5025091 ,  1.7885462 , -2.2152927 , -1.0965823 ,  2.9443574 ]],
      dtype=float32)>

## Indexing

In [82]:
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
x[:]
x[1:]
x[1:3]
x[::2]
x[::-1]
indices = tf.constant([0,6])
z = tf.gather(x, indices)
x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
x[0]
x[0:2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

## Reshaping

In [91]:
x = tf.range(9)
x = tf.reshape(x, (3,3))
x = tf.transpose(x)
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]], dtype=int32)>